# Generated by Django 5.1.3 on 2024-11-15 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PolicyIdea', '0002_policyidea_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='policy_ideas/')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='PolicyIdea.policyidea')),
            ],
        ),
    ]
