# Generated by Django 5.1.3 on 2024-11-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(default=0, max_length=6000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ing', models.BooleanField(default=0)),
            ],
        ),
    ]
