# Generated by Django 5.1.3 on 2024-11-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PolicyApp', '0003_like_rating_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
